var myString;
var myNum;
var myBool;
var myVar;
// let strArray: string[];
// let numArray: number[];
// let boolArray: boolean[];
var strArray;
var numArray;
var boolArray;
var strNumTuple;
myString = 'Hello';
myNum = 2;
myBool = true;
myVar = 0;
strArray = ['hi', 'bro'];
numArray = [1, 2];
boolArray = [true, true, false, true];
strNumTuple = ['hello', 1];
var myVoid = null;
var mynull = null;
var myundef = null;
console.log(myVoid);
console.log(mynull);
console.log(myundef);
